#!/bin/bash

# The way in which we download and/or install the YUM repository RPMs is unsafe,
# because it assumes specific versions at specific URLs.  Ideally, we would have
# a way to discover the latest versions and grab them.

on_error_die()
{
    if [ $? -ne 0 ]; then
        echo 'FAILED!'
        echo $1
        exit 1
    else
        echo 'done'
    fi
}

if [ $# -lt 1 ]; then
    echo "Requires the major version number, i.e. 3.2 for 3.2.0"
    echo "usage: $0 <major version> [testing|development]"
    exit 1
fi

if [[ $1 =~ ^[0-9]+\.[0-9]+$ ]]; then
    version=$1
else
    echo "Major version should be in the form of '<number>.<number>, i.e. 3.2"
    echo "usage: $0 <major version> [testing|development]"
    exit 1
fi

extra_repo=
case $2 in
    test|testing)     extra_repo='--enablerepo=osg-testing';;
    dev|development)  extra_repo='--enablerepo=osg-development';;
    '') ;;
    *)
        echo "$0: unknown option '$1'"
        echo "usage: $0 <major version> [testing|development]"
        exit 1
        ;;
esac

# Determine platform-specific details
release=`cat /etc/redhat-release`
case $release in
    *5.* )
        rpm_name='epel-release-5-4.noarch.rpm'
        rpm_path='http://download.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm'
        osg_name="osg-$version-el5-release-latest.rpm"
        ;;
    *6.* )
        rpm_name='epel-release-6-8.noarch.rpm'
        rpm_path='http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm'
        osg_name="osg-$version-el6-release-latest.rpm"
        ;;
    *7.* )
        rpm_name='epel-release-7-5.noarch.rpm'
        rpm_path='https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm'
        osg_name="osg-$version-el7-release-latest.rpm"
        ;;
    * )
        echo 'Could not determine OS release'
        exit 1
        ;;
esac

epel_rpm=`rpm -q epel-release 2>/dev/null`
if [ $? -eq 1 ]; then
    echo -n "Downloading $rpm_name... "
    if [ ! -f $rpm_name ]; then
        curl --fail --location --output $rpm_name --retry 10 --silent $rpm_path
        on_error_die "Could not download $rpm_name"
    else
        echo 'already downloaded'
    fi

    echo -n 'Installing epel-release... '
    rpm --install --nosignature $rpm_name
    on_error_die "Could not install $rpm_name"
else
    echo 'Already installed: epel-release'
fi

osg_rpm=`rpm -q osg-release 2>/dev/null`
if [ $? -eq 1 ]; then
    echo -n "Downloading $osg_name... "
    curl --fail --location --output $osg_name --retry 10 --silent http://repo.grid.iu.edu/osg/$version/$osg_name
    on_error_die "Could not download $osg_name"
    echo -n 'Installing osg-release... '
    rpm --install --nosignature $osg_name
    on_error_die "Could not install $osg_name"
else
    echo 'Already installed: osg-release'
fi

echo -n 'Updating osg-release... '
yum -y --quiet update osg-release
on_error_die 'Could not update osg-release'

echo -n "Install yum-priorities... "
yum -y --quiet install yum-priorities
on_error_die "Could not install yum-priorities"
echo -n 'Verify yum-priorities... '
rpm --verify yum-priorities || rpm --verify yum-plugin-priorities
on_error_die "Could not verify yum-priorities or yum-plugin-priorities"

# Always erase and install, to get latest
rpm -e osg-test >/dev/null 2>&1
echo -n "Install osg-test... "
yum -y --quiet $extra_repo install osg-test
on_error_die "Could not install osg-test"
echo -n 'Verify osg-test... '
rpm --verify osg-test
on_error_die "Could not verify osg-test"
